name: Build, Upload to test track.
on:
  push:
    branches:
      - sagar/test/internal-app-sharing
jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: 'sagar/test/internal-app-sharing'
      - name: Settting up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Runing build command
        run: ./gradlew bundleRelease
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab
      - name: Uploading mapping
        uses: actions/upload-artifact@v2
        with:
          name: mapping
          path: app/build/outputs/mapping/release/mapping.txt


  upload_to_test_track:
    name: Uploading build to test track
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Downloading mapping
        uses: actions/download-artifact@v2
        with:
          name: mapping
      - name: Uploading to test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACC_JSON }}
          packageName: 'com.sagar.materialdesigndemo'
          releaseFiles: app-release.aab
          track: internal
          mappingFile: mapping.txt
